### ISSUE TITLE
Jader, tu poderia fazer pro 3DS? Eu uso, kTeo usa, Curious usa, quase todo mundo usa o 3ds e eu sonho com esse fix.

### ISSUE THREAD

**Issue by FutonGama** [JADERLINK/Blender_Transparency_Fix_Plugin#1]
Jader, tu poderia fazer pro 3DS? Eu uso, kTeo usa, Curious usa, quase todo mundo usa o 3ds e eu sonho com esse fix.

**Comment by JADERLINK** [comment]
Infelizmente não vou ter como fazer, pois não tenho o 3dsMax e também não conheço a linguagem de script que esse programa usa.
